// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cgbc.Web.Data;

#nullable disable

namespace cgbc.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8");

            modelBuilder.Entity("cgbc.Web.Models.ConnectionCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactReasonOther")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrayerRequests")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredCommunication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WantsContact")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("SubmittedAt")
                        .IsDescending();

                    b.ToTable("ConnectionCards");
                });
#pragma warning restore 612, 618
        }
    }
}
