# Workflow for deploying CGBC SSR web application
name: Deploy CGBC Web
permissions:
  contents: read

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: [ cgbc.new/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: [ self-hosted ]
    name: Test and Deploy CGBC Web
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Generate build number
        id: buildid
        run: |
          $buildTime = (Get-Date).ToUniversalTime().ToString("yyyy.MM.dd-HH.mm")
          echo "formattedTime=$buildTime" >> $env:GITHUB_OUTPUT
      - name: Run tests for solution
        run: |
          dotnet test cgbc.new/cgbc.sln --configuration Release --logger "console;verbosity=minimal" > C:/deployment-stage/cgbc-tests-${{ steps.buildid.outputs.formattedTime }}.md 
      - name: List all changed files
        run: |
          Set-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Build Results for CGBC"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Build Number - ${{ steps.buildid.outputs.formattedTime }}"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Commit Item Messages:"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          $mergeCommit = git log --format=%B -n 1 HEAD
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value $mergeCommit
          $parentCount = (git cat-file -p HEAD | Select-String "^parent").Count
          if ($parentCount -gt 1) {
            Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
            Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Included Commits:"
            $prCommits = git log --format="- %s" HEAD^1..HEAD^2
            Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ($prCommits -join "`n")
          }
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Changed Files"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value $(git diff --name-status HEAD~1..HEAD)
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Test Results:"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value (Get-Content -Path C:/deployment-stage/cgbc-tests-${{ steps.buildid.outputs.formattedTime }}.md)
      - name: Create Backup
        run: |
          New-Item -ItemType "directory" -Path "C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }}/" -Force
          Copy-Item C:/www-root/cedargrovebaptist.church/* -Destination C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }}/ -Recurse
          Compress-Archive -Path "C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }}/*" -Update -DestinationPath C:/backups/cgbc-${{ steps.buildid.outputs.formattedTime }}.zip -CompressionLevel "Fastest"
          Remove-Item -Path C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }} -Recurse
      - name: Stop IIS Site
        run: |
          Import-Module WebAdministration
          if ((Get-WebAppPoolState -Name "CedarGroveBaptist" -ErrorAction SilentlyContinue).Value -eq "Started") {
            Stop-WebAppPool -Name "CedarGroveBaptist"
            Start-Sleep -Seconds 3
          }
      - name: Deploy CGBC application
        run: |
          cd cgbc.new/cgbc.Web
          dotnet publish -c Release -o C:/www-root/cedargrovebaptist.church
      - name: Start IIS Site
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "CedarGroveBaptist"
      - name: Email Notification
        run: |
          cd  D:/it-tools/mailer
          ./SesMailer.exe --to  "David Nuckolls <david.nuckolls@glorykidd.com>" --subject "CGBC Release ${{ steps.buildid.outputs.formattedTime }}" --body C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt --format text  --from-display-name "CGBC Website"
